indir: "input"
outdir: "output"
samples:
    - A01
    - A02
    - A03
    - A04
    - A05
    - A06
    - A07
    - A08
depths:
    - 10000000
    - 6666666
    - 1000000
    - 666666
trims:
    - 0
    - 50